### ISSUE TITLE
Nugets not available

### ISSUE THREAD

**Issue by KillianDhe** [MarkKharitonov/NuGetPCToPRMigrator#1]
Hello, 

I have a solution with more than a hundred project that I'd like to migrate to packageReference without loosing a day ^^.
I wanted to try your solution but unfortunately your nugets repository links seems dead, so we can't restore the nugets.

And as the nuget are not provided in the source, there is no way for us to make this project compile.

Is it possible to edit the nuget repo source or to provide the needed .nupkg?

Thank you and have a good day.

**Comment by stanimirsellercloud** [comment]
@KillianDhe How did you manage to resolve this? 

@MarkKharitonov Is it possible to publish or share these packages?
